version: '3.8'

services:
  backend:
    build:
      context: ./student-manager-backend
    ports:
      - "5051:5051"
    env_file:
      - ./student-manager-backend/.env
    volumes:
      - ./student-manager-backend:/app

  frontend:
    build:
      context: ./student-manager
    ports:
      - "8501:8501"
    env_file:
      - ./student-manager/.env
    volumes:
      - ./student-manager:/app
    depends_on:
      - backend
